"""initial schema

Revision ID: c8260f3900e0
Revises: 
Create Date: 2026-08-26 02:37:28.705096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8260f3900e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=120), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('split', sa.String(length=20), nullable=True),
    sa.Column('natural_model', sa.String(length=200), nullable=True),
    sa.Column('program_model', sa.String(length=200), nullable=True),
    sa.Column('verifier_model', sa.String(length=200), nullable=True),
    sa.Column('independence', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_run_id'), 'experiments', ['run_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('fiscal_year', sa.String(length=20), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieved_on', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=True)
    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('arm', sa.String(length=20), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('stratum', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('ci_low', sa.Float(), nullable=True),
    sa.Column('ci_high', sa.Float(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'arm', 'metric', 'stratum', name='uq_result')
    )
    op.create_index(op.f('ix_evaluation_results_arm'), 'evaluation_results', ['arm'], unique=False)
    op.create_index(op.f('ix_evaluation_results_metric'), 'evaluation_results', ['metric'], unique=False)
    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('canonical', sa.Numeric(precision=38, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('scale', sa.String(length=30), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('year_source', sa.String(length=40), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=400), nullable=True),
    sa.Column('table_index', sa.Integer(), nullable=True),
    sa.Column('row_label', sa.String(length=400), nullable=False),
    sa.Column('column_label', sa.String(length=200), nullable=True),
    sa.Column('column_index', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.String(length=120), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_id', 'row_label', 'column_index', name='uq_fact_cell')
    )
    op.create_index('ix_fact_metric_year', 'financial_facts', ['metric', 'year'], unique=False)
    op.create_index(op.f('ix_financial_facts_chunk_id'), 'financial_facts', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_financial_facts_metric'), 'financial_facts', ['metric'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('printed_number', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'number', name='uq_page')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qid', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=300), nullable=True),
    sa.Column('fiscal_year', sa.String(length=20), nullable=True),
    sa.Column('question_type', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('ambiguous', sa.Boolean(), nullable=False),
    sa.Column('split', sa.String(length=20), nullable=False),
    sa.Column('gold_text', sa.String(length=120), nullable=True),
    sa.Column('gold_unit', sa.String(length=60), nullable=True),
    sa.Column('gold_canonical', sa.Numeric(precision=38, scale=6), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('validator', sa.String(length=200), nullable=True),
    sa.Column('validated_on', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_qid'), 'questions', ['qid'], unique=True)
    op.create_index(op.f('ix_questions_split'), 'questions', ['split'], unique=False)
    op.create_index(op.f('ix_questions_validation_status'), 'questions', ['validation_status'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=120), nullable=True),
    sa.Column('context_scale', sa.String(length=30), nullable=True),
    sa.Column('context_currency', sa.String(length=10), nullable=True),
    sa.Column('parsing_accuracy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_chunk_id'), 'tables', ['chunk_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('arm', sa.String(length=20), nullable=False),
    sa.Column('answer_text', sa.String(length=200), nullable=True),
    sa.Column('canonical', sa.Numeric(precision=38, scale=6), nullable=True),
    sa.Column('answer_source', sa.String(length=40), nullable=True),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('agreed', sa.Boolean(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('stratum', sa.String(length=30), nullable=True),
    sa.Column('latency_seconds', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'question_id', 'arm', name='uq_answer')
    )
    op.create_index(op.f('ix_answers_arm'), 'answers', ['arm'], unique=False)
    op.create_index(op.f('ix_answers_stratum'), 'answers', ['stratum'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=120), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('printed_page', sa.Integer(), nullable=True),
    sa.Column('anchors', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hallucination_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('label_confidence', sa.String(length=30), nullable=False),
    sa.Column('counts_as_hallucination', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hallucination_events_kind'), 'hallucination_events', ['kind'], unique=False)
    op.create_index(op.f('ix_hallucination_events_provenance'), 'hallucination_events', ['provenance'], unique=False)
    op.create_table('program_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('value', sa.String(length=120), nullable=True),
    sa.Column('canonical', sa.Numeric(precision=38, scale=6), nullable=True),
    sa.Column('program', sa.Text(), nullable=True),
    sa.Column('execution_status', sa.String(length=40), nullable=True),
    sa.Column('validation_violations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reasoning_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('value', sa.String(length=120), nullable=True),
    sa.Column('canonical', sa.Numeric(precision=38, scale=6), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.String(length=40), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_runs')
    op.drop_table('reasoning_runs')
    op.drop_table('program_runs')
    op.drop_index(op.f('ix_hallucination_events_provenance'), table_name='hallucination_events')
    op.drop_index(op.f('ix_hallucination_events_kind'), table_name='hallucination_events')
    op.drop_table('hallucination_events')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_answers_stratum'), table_name='answers')
    op.drop_index(op.f('ix_answers_arm'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_tables_chunk_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_table('sections')
    op.drop_index(op.f('ix_questions_validation_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_split'), table_name='questions')
    op.drop_index(op.f('ix_questions_qid'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('pages')
    op.drop_index(op.f('ix_financial_facts_metric'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_chunk_id'), table_name='financial_facts')
    op.drop_index('ix_fact_metric_year', table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_index(op.f('ix_evaluation_results_metric'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_arm'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_index(op.f('ix_experiments_run_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_table('companies')
    # ### end Alembic commands ###
